<a href="https://colab.research.google.com/github/Deusmaxz/MachineLearning/blob/main/Week8/Week8_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn import svm
from sklearn.svm import SVC
import sklearn
import numpy as np
from array import array
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)
SVC()

SVC()

In [19]:
clf.predict([[2., 2.]])

array([1])

In [20]:
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [21]:
clf.support_

array([0, 1], dtype=int32)

In [22]:
clf.n_support_

array([1, 1], dtype=int32)

In [23]:
X = [[0], [1], [2], [3]]
Y = [0, 1, 2, 3]
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X, Y)

SVC(decision_function_shape='ovo')

In [24]:
dec = clf.decision_function([[1]])
dec.shape[1] # 4 classes: 4*3/2 = 6

6

In [25]:
clf.decision_function_shape = "ovr"
dec = clf.decision_function([[1]])
dec.shape[1] 

4

In [26]:
lin_clf = svm.LinearSVC()
lin_clf.fit(X, Y)

LinearSVC()

In [27]:
dec = lin_clf.decision_function([[1]])
dec.shape[1]

4

In [28]:
from sklearn import svm
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
regr = svm.SVR()
regr.fit(X, y)

SVR()

In [29]:
regr.predict([[1, 1]])

array([1.5])

In [30]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

clf = make_pipeline(StandardScaler(), SVC())

In [31]:
linear_svc = svm.SVC(kernel='linear')
linear_svc.kernel

'linear'

In [32]:
import numpy as np
from sklearn import svm
def my_kernel(X, Y):
  return np.dot(X, Y.T)
clf = svm.SVC(kernel=my_kernel)

In [33]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm
X, y = make_classification(n_samples=10, random_state=0)
X_train , X_test , y_train, y_test = train_test_split(X, y, random_state=0)
clf = svm.SVC(kernel='precomputed')
# linear kernel computation
gram_train = np.dot(X_train, X_train.T)
clf.fit(gram_train, y_train)

SVC(kernel='precomputed')

In [34]:
# predict on training examples
gram_test = np.dot(X_test, X_train.T)
clf.predict(gram_test)

array([0, 1, 0])